apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakRealm
metadata:
  name: members
spec:
  keycloak: keycloak-{{ .Release.Namespace }}
  realm: members
  roles:
  - admin
  - member
  - service
  - gdd
  - db
  - fcf
  - fsf
  - md
  - lp
