apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jx-postgresql-ha-postgresql
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: jx
      app.kubernetes.io/name: postgresql-ha
