domain: &domain cloudnativeentrepreneur.com

PipelineSecrets: {}
auth:
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      persistence:
        dbHost: jx-postgresql-ha-pgpool.jx-production.svc.cluster.local
        existingSecret: auth-postgres
        existingSecretPasswordKey: adminPassword
        existingSecretUsernameKey: adminUsername
      replicas: 3
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      username: vault:production/auth/postgres:adminUsername
  keycloakAdminPassword: vault:production/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:production/auth/keycloak:adminUsername
  postgresAdminPassword: vault:production/auth/postgres:adminPassword
  postgresAdminUsername: vault:production/auth/postgres:adminUsername
  postgresql-ha:
    global:
      pgpool:
        adminPassword: vault:production/auth/postgres:pgpoolAdminPassword
        adminUsername: vault:production/auth/postgres:pgpoolAdminUsername
      postgresql:
        database: keycloak
        password: vault:production/auth/postgres:adminPassword
        repmgrPassword: vault:production/auth/postgres:repmgrPassword
        repmgrUsername: vault:production/auth/postgres:repmgrUsername
        username: vault:production/auth/postgres:adminUsername
    metrics:
      resources:
        limits:
          cpu: 50m
          memory: 20Mi
        requests:
          cpu: 50m
          memory: 20Mi
    persistence:
      storageClass: ssd-retain
      size: 20Gi
    pgpool:
      replicaCount: 3
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
    postgresql:
      replicaCount: 3
      resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
demo-app:
  keycloak:
    keycloak: keycloak-jx-production
    redirectUris:
      allowAll: false
      includeNamespace: false
      domain: *domain
      serviceName: demo-app
    url: https://auth.cloudnativeentrepreneur.com
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: *domain
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-com-p
    tlsacme: "true"
    urltemplate: '{{.Service}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
