PipelineSecrets: {}
auth:
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      persistence:
        dbHost: production-postgresql.jx-production.svc.cluster.local
        dbName: keycloak
        dbVendor: postgres
        existingSecret: keycloak.production-postgresql.credentials.postgresql.acid.zalan.do
        existingSecretPasswordKey: password
        existingSecretUsernameKey: username
      podDisruptionBudget:
        maxUnavailable: 1
      priorityClassName: production
      replicas: 5
      resources:
        limits:
          cpu: "1"
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 512Mi
      username: vault:production/auth/postgres:adminUsername
  keycloakAdminPassword: vault:production/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:production/auth/keycloak:adminUsername
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
content:
  cors:
    origin: cloudnativeentrepreneur.com
  deployDomain: cloudnativeentrepreneur.com
  keycloak:
    keycloak: keycloak-jx-production
    realm: members
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.com
      includeNamespace: false
      serviceName: content
    url: https://auth.cloudnativeentrepreneur.com
  session:
    key: vault:production/auth/session:key
demo-app:
  keycloak:
    keycloak: keycloak-jx-production
    realm: members
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.com
      includeNamespace: false
      serviceName: demo-app
    url: https://auth.cloudnativeentrepreneur.com
domain: cloudnativeentrepreneur.com
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.com
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-com-p
    tlsacme: "true"
    urltemplate: '{{.Service}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
www:
  env:
    SAPPER_CLIENT_CONTENT_GRAPHQL_URL: https://content.cloudnativeentrepreneur.com/graphql
    SAPPER_SERVER_CONTENT_GRAPHQL_URL: http://content.jx-production.svc.cluster.local/graphql
    SAPPER_GTM_TRACKING_ID: vault:production/gtm:trackingId
  keycloak:
    keycloak: keycloak-jx-production
    realm: members
    redirectUris:
      allowAll: false
      allowLocalhost: false
      domain: cloudnativeentrepreneur.com
      includeNamespace: false
      serviceName: www
    url: https://auth.cloudnativeentrepreneur.com
  session:
    key: vault:production/auth/session:key
