PipelineSecrets: {}
auth:
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      persistence:
        dbVendor: postgres
        dbHost: jx-patroni.jx-production.svc.cluster.local
        dbName: keycloak
        dbUser: keycloak
        dbPassword: vault:production/patroni:keycloak
      podDisruptionBudget:
        maxUnavailable: 1
      priorityClassName: production
      replicas: 3
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      username: vault:production/auth/postgres:adminUsername
  keycloakAdminPassword: vault:production/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:production/auth/keycloak:adminUsername
  
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
demo-app:
  keycloak:
    keycloak: keycloak-jx-production
    realm: members
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.com
      includeNamespace: false
      serviceName: demo-app
    url: https://auth.cloudnativeentrepreneur.com
domain: cloudnativeentrepreneur.com
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.com
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-com-p
    tlsacme: "true"
    urltemplate: '{{.Service}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
patroni:
  credentials:
    superuser: vault:production/patroni:superuser
    admin: vault:production/patroni:admin
    standby: vault:production/patroni:standby
  persistentVolume:
    storageClass: ssd-retain
    size: 8Gi
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi
prow: {}
