PipelineSecrets: {}
auth:
  keycloak:
    keycloak:
      existingSecret: auth-keycloak
      existingSecretKey: adminPassword
      persistence:
        dbHost: jx-postgresql-ha-pgpool.jx-production.svc.cluster.local
        existingSecret: auth-postgres
        existingSecretPasswordKey: adminPassword
        existingSecretUsernameKey: adminUsername
      podDisruptionBudget:
        maxUnavailable: 1
      priorityClassName: production
      replicas: 3
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      username: vault:production/auth/postgres:adminUsername
  keycloakAdminPassword: vault:production/auth/keycloak:adminPassword
  keycloakAdminUsername: vault:production/auth/keycloak:adminUsername
  postgresAdminPassword: vault:production/auth/postgres:adminPassword
  postgresAdminUsername: vault:production/auth/postgres:adminUsername
  postgresql-ha:
    global:
      pgpool:
        adminPassword: vault:production/auth/postgres:pgpoolAdminPassword
        adminUsername: vault:production/auth/postgres:pgpoolAdminUsername
      postgresql:
        database: keycloak
        password: vault:production/auth/postgres:adminPassword
        repmgrPassword: vault:production/auth/postgres:repmgrPassword
        repmgrUsername: vault:production/auth/postgres:repmgrUsername
        username: vault:production/auth/postgres:adminUsername
    metrics:
      resources:
        limits:
          cpu: 50m
          memory: 20Mi
        requests:
          cpu: 50m
          memory: 20Mi
    persistence:
      size: 20Gi
      storageClass: ssd-retain
    pgpool:
      pdb:
        create: true
        minAvailable: null
        maxUnavailable: 1
      priorityClassName: production
      replicaCount: 3
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 256Mi
    postgresql:
      pdb:
        create: true
        minAvailable: null
        maxUnavailable: 1
      priorityClassName: production
      replicaCount: 3
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 256Mi
  realms:
    dev: dev
    members: members
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
demo-app:
  keycloak:
    keycloak: keycloak-jx-production
    realm: members
    redirectUris:
      allowAll: false
      domain: cloudnativeentrepreneur.com
      includeNamespace: false
      serviceName: demo-app
    url: https://auth.cloudnativeentrepreneur.com
domain: cloudnativeentrepreneur.com
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: cloudnativeentrepreneur.com
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-cloudnativeentrepreneur-com-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
jenkins:
  Servers:
    Global: {}
prow: {}
